# Estudo de caso - Diabetes dos Índios Pima - Parte 02

## Começando a limpeza dos dados - A

### Instalando e Carregando os pacotes

In [1]:
# Imports
import math
import pandas as pd
import numpy as np

# Criando uma lista para identificar valores ausentes
lista_labels_valores_ausentes = ["n/a", "na", "NA", "undefined"]

# Carrega o dataset
dataset = pd.read_csv("data/diabetes.csv", na_values = lista_labels_valores_ausentes)

# Importando 'limpeza_dados.py' e suas funções
from funcoes_limpeza_dados.limpeza_dados import *

### Limpeza dos Dados - A

In [2]:
# Verificar os valores ausentes no dataset
dataset.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [3]:
# Verificando os valores ausentes no dataset com as funções:
# Porcentual total de valores ausentes
calcula_porcentagem_valores_ausentes(dataset)

O conjunto de dados tem 0.0% de valores ausentes.

In [4]:
# Porcentagem de valores ausentes por coluna
relatorio_valores_ausentes_por_coluna(dataset)

O conjunto de dados tem 9 colunas.
Foram encontradas 0 colunas com valores ausentes.

Empty DataFrame
Columns: [Quantidade de Ausentes, Porcentagem de Ausentes, Tipo de Dado]
Index: []

In [5]:
dataset.sample(30)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
239,0,104,76,0,0,18.4,0.582,27,0
75,1,0,48,20,0,24.7,0.140,22,0
271,2,108,62,32,56,25.2,0.128,21,0
765,5,121,72,23,112,26.2,0.245,30,0
263,3,142,80,15,0,32.4,0.200,63,0
82,7,83,78,26,71,29.3,0.767,36,0
544,1,88,78,29,76,32.0,0.365,29,0
102,0,125,96,0,0,22.5,0.262,21,0
365,5,99,54,28,83,34.0,0.499,30,0
539,3,129,92,49,155,36.4,0.968,32,1
308,0,128,68,19,180,30.5,1.391,25,1
513,2,91,62,0,0,27.3,0.525,22,0
287,1,119,86,39,220,45.6,0.808,29,1
115,4,146,92,0,0,31.2,0.539,61,1
67,2,109,92,0,0,42.7,0.845,54,0
581,6,109,60,27,0,25.0,0.206,27,0
202,0,108,68,20,0,27.3,0.787,32,0
497,2,81,72,15,76,30.1,0.547,25,0
142,2,108,52,26,63,32.5,0.318,22,0
532,1,86,66,52,65,41.3,0.917,29,0
105,1,126,56,29,152,28.7,0.801,21,0
601,6,96,0,0,0,23.7,0.190,28,0
251,2,129,84,0,0,28.0,0.284,27,0
695,7,142,90,24,480,30.4,0.128,43,1
437,5,147,75,0,0,29.9,0.434,28,0
610,3,106,54,21,158,30.9,0.292,24,0
431,3,89,74,16,85,30.4,0.551,38,0
531,0,107,76,0,0,45.3,0.686,24,0
505,10,75,82,0,0,33.3,0.263,38,0
110,3,171,72,33,135,33.3,0.199,24,1

In [6]:
# Verificando o toal de valores iguais a zero por coluna
dataset.apply(lambda x: (x==0).sum())

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                     500
dtype: int64

Aqui não se trata de um dataset com valores nulos (ausência de dados). **Aqui é o caso de ausência de informação**.

In [7]:
# Alterando essa ausência de informação em ausência de dados!
# coluna GLUCOSE
dataset["Glucose"] = dataset["Glucose"].apply(lambda x: np.nan if x == 0 else x)
# coluna BLOODPRESSURE
dataset["BloodPressure"] = dataset["BloodPressure"].apply(lambda x: np.nan if x == 0 else x)
# coluna SKINTHICKNESS
dataset["SkinThickness"] = dataset["SkinThickness"].apply(lambda x: np.nan if x == 0 else x)
# coluna INSULIN
dataset["Insulin"] = dataset["Insulin"].apply(lambda x: np.nan if x == 0 else x)
# coluna BMI
dataset["BMI"] = dataset["BMI"].apply(lambda x: np.nan if x == 0 else x)

In [8]:
dataset.isnull().sum()

Pregnancies                   0
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [9]:
# Verificando os valores ausentes no dataset com as funções, após a alteração:

# Porcentual total de valores ausentes
calcula_porcentagem_valores_ausentes(dataset)

O conjunto de dados tem 9.43% de valores ausentes.

In [10]:
# Porcentagem de valores ausentes por coluna
relatorio_valores_ausentes_por_coluna(dataset)

O conjunto de dados tem 9 colunas.
Foram encontradas 5 colunas com valores ausentes.

               Quantidade de Ausentes  Porcentagem de Ausentes Tipo de Dado
Insulin                           374                    48.70      float64
SkinThickness                     227                    29.56      float64
BloodPressure                      35                     4.56      float64
BMI                                11                     1.43      float64
Glucose                             5                     0.65      float64

### Salvando os dados desta etapa

In [11]:
dataset.to_csv("data/dataset_parte2.csv")

## Fim da segunda parte do projeto